name: exercise_sustainability
version: 1.0.0
config-version: 2
profile: exercise_sustainability

model-paths:    [models]
analysis-paths: [analyses]
test-paths:     [tests]
seed-paths:     [seeds]
macro-paths:    [macros]
snapshot-paths: [snapshots]

clean-targets:
  - target
  - dbt_packages

on-run-start:
  - "create schema if not exists {{ target.database }}.{{ target.schema }}"

models:
  exercise_sustainability:
    +materialized: view
    staging:
      +materialized: view
      +schema: staging
      +tags: ['staging']
    intermediate:
      +materialized: view
      +schema: intermediate
      +tags: ['intermediate']
    marts:
      +materialized: table
      +schema: marts
      +tags: ['marts']